# Generated by Django 6.0.2 on 2026-02-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('school', 'School'), ('ojt', 'OJT'), ('capstone', 'Capstone'), ('cert', 'Certification'), ('project', 'Project')], default='school', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-date', '-id'],
            },
        ),
    ]
