# Generated by Django 6.0.2 on 2026-02-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('issuer', models.CharField(max_length=120)),
                ('year', models.CharField(blank=True, max_length=10)),
                ('credential_url', models.URLField(blank=True)),
                ('badge_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['-year', 'title'],
            },
        ),
    ]
